### ISSUE TITLE
Hoxy's implementation of cheerio is incompatible with XHTML

### ISSUE THREAD

**Issue by sholladay** [greim/hoxy#34]
Took some digging to figure out why some specific pages were not rendering correctly for me. Turns out it is due to how cheerio is implemented for as:'$' intercepts. The pages were using XML-flavored markup and hoxy always instructs cheerio to render HTML, causing syntax errors which are only detected client-side.

**Test case:**
Spin up hoxy with an empty intercept like this (does not need to edit the response):
```javascript
proxy.intercept(
    {
        phase    : 'response',   // run before we send anything back to the client
        as       : '$'           // ask for a cheerio object, to manipulate DOM
    },
    function (req, resp) {
    }
);
```
Then visit a page with XML, such as:
 - http://www.skechers.com
 - http://www.synergycons.com/tutorials/xhtml2.asp (visual alert when it is broken!)

**Responsible code**:
Line 26 in `lib/dom-reader.js`:
```javascript
DomReader.prototype.toString = function(){
  return this._$.html();  // line 26
};
```
Changing that to...
```javascript
  return this._$.xml();
```
...fixes the problem.

But of course this has negative side-effects for non-XML pages. Seems like something that needs some thoughtful design and automated tests. The MIME type listed in HTTP headers often is not correct, so I'm not sure at the moment how to make this reliable without a lot of overhead. It *could* parse and render an exact copy with both strategies internally and then detect which one caused the least amount of change... ;)

**Comment by sholladay** [comment]
FYI, I have posted a bounty for this issue on Bountysource.
https://www.bountysource.com/issues/6593289-hoxy-s-implementation-of-cheerio-is-incompatible-with-xhtml

My research indicates that this is going to be more problematic.
1. It looks like we must make the decision about XML vs HTML prior to doing cheerio.load() and then pass xmlMode:true into the .load method, based on that decision.
2. Even I am incorrect about #1, I have not yet found a way to access the doctype from within cheerio, which would be my preferred way.
3. If we have to resort to string searching for the doctype, experience has shown me it will be error prone - for example, some pages set the doctype based on conditional comments to make IE behave differently. So searching the string for the correct instance is not easy. Though, we can *probably* assume they wouldn't switch between HTML vs XHTML like this. So maybe its a moot point.

**Comment by greim** [comment]
Nice! Well if someone jumps in with an acceptable fix then I'll certainly review and merge it in. Otherwise I may take a crack at it soon.

Now that you mention it I suspect `xmlMode:true` should be set for any actual xml mime-type, regardless of doctype, since in that case you'd truly want to parse it as XML (with the caveat that cheerio isn't a conforming parser). Likewise set it `false` for any non-xml mime type since then we're likely dealing with tag soup and would not want cheerio to treat `<script>` content as markup, etc.

**Comment by greim** [comment]
Take a look at the branch `cheerio-xml`.

Basically, if the mime type is xml, cheerio will parse with `xmlMode:true`, otherwise `xmlMode:false`.

NOTE: if the markup contains an xhtml doctype but is sent with a non-xml mime type, it will be parsed with `xmlMode:false`. This is because with `xmlMode:true`, per the htmlparser2 docs, `<script>` and `<style>` content would be treated as markup, which would screw up a lot pages.

Then, if the doctype is xhtml OR if the mime type is xml, then it will output `xml()`, otherwise `html()`. Doctype is gotten from cheerio, although in a sort of roundabout way. (see https://github.com/cheeriojs/cheerio/issues/640) Also added a few tests in this branch.

**Comment by greim** [comment]
(Pasted from a PR thread) It looks like cheerio has fundamental issues with XML.

```js
// test.js
var cheerio = require('cheerio')
var input = '<foo title="foo &amp; bar"/>'
var $ = cheerio.load(input,{xmlMode:true})
var output = $.xml()
console.log(input)
console.log(output)
```

```
$ node test.js
<foo title="foo &amp; bar"/>
<foo title="foo & bar"/>
```

For tag soup pages this shouldn't matter, but sketchers.com uses a client-side XSL transform and errors like the above completely break the page. I don't know if there's a way to force cheerio to conform more strictly, beyond what's shown above. Draconian xml compliance is probably not on their radar.

**Comment by sholladay** [comment]
Thanks for the work on this. Feel free to claim the bounty: https://www.bountysource.com/issues/6593289-hoxy-s-implementation-of-cheerio-is-incompatible-with-xhtml/developers
