### ISSUE TITLE
Pass cycle to intercept callback instead of binding the callback to it

### ISSUE THREAD

**Issue by nerdbeere** [greim/hoxy#42]
**Disclaimer**: This is more like a suggestion I'd like to discuss.

Currently the callback that a user of hoxy passes to the intercept method is bound to an instance of cycle.

With es6 I'd like to define my callback using fat arrow functions to bind my current scope to the callback.
In order to achieve this at the moment, my code looks something like this:

```javascript
proxy.intercept('request', function(req, res, done) {
  that._onInterceptRequest(req, res, this, done);
});
```

My suggestion would be to pass the cycle to the callback (like I do) instead of binding it to the callback.
While I agree that this changes the API, maybe the rewrite might be a good opportunity to do that.

**Comment by greim** [comment]
It would be a breaking change since it messes with callback arity, which hoxy relies on as a signal for async (similar to mocha).

I like the idea however since I'm also using arrows a lot these days. Once 2.x is out, I'd like to look at a 3.x in which among other things the `done()` callback/arity hack goes away completely and the third arg is freed up. Async would be accomplished by returning either a promise or an iterator from the callback. ([co](https://www.npmjs.com/package/co) would be used transmute the iterator to a promise in the latter case).

Although I'm inclined to continue passing the cycle as `this` for those that prefer that use case, even if redundantly passing it as a third arg.

**Comment by greim** [comment]
3.0 is published now.
